version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"
