name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: ['10.*', '11.*', '12.*']
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 11.*
            php: 8.1            
          - laravel: 12.*
            php: 8.1

    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update -n
          composer update --${{ matrix.dependency-version }} --no-suggest --prefer-dist -n -o

      - name: Run tests
        run: vendor/bin/phpunit
